export const NLS_FR = {
  siteLanguagePack: {
    language: "fr" as const,
    locale: "fr-FR",
    stepLabels: ["Mariage", "Style", "Photos", "Galerie", "Aperçu", "Compte"],
    menuLabels: {
      home: "Accueil",
      gifts: "Cadeaux",
      story: "Histoire",
      gallery: "Photos",
      accommodation: "Hébergement",
      location: "Lieux",
      program: "Programme",
    },
    texts: {
      heroSubtitle: "Le Mariage de",
      heroCta: "Confirmer votre présence",
      rsvpTitle: "CONFIRMEZ VOTRE PRÉSENCE",
      rsvpDescription: "Nous serions ravis de vous compter parmi nous",
      rsvpButton: "Je confirme ma présence",
      navRsvp: "RSVP",
      navCagnotte: "Cagnotte",
      locationTitle: "LIEU & ACCÈS",
      locationDescription: "Toutes les informations pour nous rejoindre",
      accommodationTitle: "HÉBERGEMENT À PROXIMITÉ",
      accommodationDescription: "Retrouvez ici quelques adresses utiles pour loger à proximité.",
      programTitle: "DÉROULEMENT",
      programDescription: "Le programme de notre journée",
      storyTitle: "NOTRE HISTOIRE",
      storyBody: "Leur histoire a commencé il y a quelques années, une rencontre simple qui s'est transformée en une belle aventure. Aujourd'hui, ils s'apprêtent à dire 'Oui' entourés de leurs proches.",
      galleryTitle: "GALERIE PHOTOS",
      galleryDescription: "Quelques instants capturés avant le grand jour.",
      giftsTitle: "LISTE DE CADEAUX",
      giftsDescription: "Quelques idées pour ceux qui souhaitent nous faire plaisir.",
      cagnotteTitle: "CAGNOTTE MARIAGE",
      cagnotteDescription: "Votre présence est notre plus beau cadeau. Si vous souhaitez contribuer à notre voyage de noces ou à notre nouveau départ, vous pouvez participer à notre cagnotte.",
      cagnotteBackLabel: "Retour",
      cagnotteSubmitLabel: "Contribuer",
      invitationGreeting: "Nous avons l'honneur de vous convier",
      invitationPrelude: "à célébrer l'union de",
      invitationMessage: "Ce jour ne serait pas le même sans votre présence à nos côtés.",
      invitationSubmessage: "Venez comme vous êtes, avec le cœur léger et l'envie de faire la fête.",
      invitationCagnotteTitle: "Liste de mariage",
      invitationCagnotteDescription: "Votre présence est le plus beau des cadeaux. Si toutefois vous souhaitez contribuer, une cagnotte a été mise en place pour nous aider à construire notre avenir.",
      invitationCagnotteButton: "Contribuer",
      invitationFooterNote: "Merci de confirmer votre présence avant la date indiquée. Nous avons hâte de vous retrouver.",
      footerTitle: "On a hâte de vous voir",
      footerSubtitle: "Merci de faire partie de cette aventure.",
      footerCopyright: "© 2026. Tous droits réservés.",
    },
    sections: {
      locationItems: [
        { title: "Cérémonie civile", address: "Mairie de Lille — 10 Rue Pierre Mauroy", description: "Rendez-vous à 14h30 pour accueillir les invités." },
        { title: "Réception", address: "Château de la Verrière — Salle des Roses", description: "Cocktail et dîner à partir de 18h." },
      ],
      programItems: [
        { time: "14:30", title: "Accueil des invités", description: "Installation et photos de famille." },
        { time: "15:00", title: "Cérémonie", description: "Échange des vœux et sortie des mariés." },
        { time: "18:30", title: "Cocktail & Dîner", description: "Apéritif, repas et animations." },
      ],
    },
    invitation: {
      pageTitle: "Invitation",
      loading: "Chargement...",
      notFoundTitle: "Invitation non trouvée",
      notFoundDescription: "Vérifiez le lien ou contactez les mariés.",
      people: "personnes",
      person: "personne",
      table: "Table",
      invitationType: "Type d'invitation",
      checkInLink: "Lien check-in",
    },
  },
  adminLayout: {
    brand: "Daylora Admin",
    back: "Retour",
    design: "Design",
    languageLabel: "Langue",
    languageFr: "FR",
    languageEn: "EN",
    editLive: "Modifier en live",
    viewSite: "Voir le site",
    helpCenter: "Centre d'aide",
    weddingManagement: "Gestion du mariage",
    logout: "Déconnexion",
    logoutTitle: "Se déconnecter",
    pageLabels: {
      templates: "Templates",
      design: "Édition live",
      guests: "Invités",
      guestExperience: "Expérience invités",
      billing: "Facturation",
      gifts: "Cadeaux",
      site: "Site & Menus",
      checkInOps: "Check-in Jour J",
      home: "Accueil",
      fallback: "Espace Daylora",
    },
    nav: {
      home: "Accueil",
      dashboard: "Dashboard",
      design: "Design",
      guests: "Invités",
      guestExperience: "Expérience invités",
      checkInOps: "Check-in Jour J",
      templates: "Templates",
      site: "Site & Menus",
      gifts: "Cadeaux",
      emails: "Emails",
      billing: "Facturation",
      feedback: "Avis",
      settings: "Paramètres",
    },
  },
  dashboard: {
    welcomeSuffix: "votre histoire commence ici.",
    welcomeSubtitle: "Bienvenue dans la création de votre journée inoubliable",
    congratulationsSuffix: "votre belle histoire continue.",
    weddingHappened: "Votre mariage a eu lieu — profitez de chaque souvenir.",
    countdownLabel: "Jour J dans",
    countdownDay: "jour",
    countdownDays: "jours",
    nextStepLabel: "Prochaine étape",
    steps: {
      chooseDesign: "Choisir un design",
      chooseDesignDesc: "Sélectionnez un template pour donner vie à votre site.",
      completeInfo: "Compléter les informations",
      completeInfoDesc: "Ajoutez la date et les détails de votre mariage.",
      addGuests: "Ajouter vos invités",
      addGuestsDesc: "Commencez à constituer votre liste d'invités.",
      publish: "Publier votre site",
      publishDesc: "Votre site est prêt — partagez-le avec vos proches.",
    },
    linkCopied: "Lien copié",
    fullMode: "Mode complet",
    simplify: "Simplifier",
    kpis: {
      guests: "Invités",
      guestsHint: "RSVP reçus",
      confirmed: "Confirmés",
      confirmedHint: "Présences",
      pending: "En attente",
      pendingHint: "À relancer",
      declined: "Refusés",
      declinedHint: "Indisponibles",
    },
    tour: {
      welcomeTitle: "Bienvenue sur Daylora !",
      welcomeDesc: "Ici vous retrouvez un message personnalisé et le lien vers votre site de mariage.",
      statsTitle: "Vos statistiques",
      statsDesc: "Suivez en un coup d'œil le nombre d'invités, les confirmations et les refus.",
      progressTitle: "Votre progression",
      progressDesc: "Cette checklist vous guide étape par étape. Suivez-la pour avoir un site parfait !",
    },
  },
  checklist: {
    title: "Votre progression",
    completedSteps: "{done} sur {total} étapes complétées",
    cta: "Faire",
    steps: {
      template: {
        label: "Choisir un design",
        description: "Sélectionnez le template parfait pour votre mariage",
      },
      info: {
        label: "Informations clés",
        description: "Date, lieu et histoire de votre couple",
      },
      guests: {
        label: "Ajouter des invités",
        description: "Importez ou ajoutez votre liste d'invités",
      },
      features: {
        label: "Activer les modules",
        description: "Cagnotte, liste de cadeaux, livre d'or",
      },
      publish: {
        label: "Publier le site",
        description: "Rendez votre site visible pour vos invités",
      },
    },
  },
  widgets: {
    availability: {
      present: "Présents",
      absent: "Absents",
      pending: "En attente",
    },
    partySize: {
      solo: "Solo (1)",
      couple: "Couple (2)",
    },
    tablePlan: {
      assigned: "Attribués",
      unassigned: "Non attribués",
    },
    cards: {
      totalGuests: "Total invités",
      totalGuestsDesc: "{count} réponses",
      declined: "Absents",
      declinedDesc: "Invités indisponibles",
      confirmed: "Confirmés",
      confirmedDesc: "{count} personnes totales",
      siteDesign: "Site & design",
      siteDesignValue: "Personnaliser",
      siteDesignDesc: "Éditez votre site",
      clickToFilter: "(cliquer pour filtrer)",
    },
    charts: {
      availability: "Répartition disponibilité",
      groupSize: "Taille des groupes",
      tablePlan: "Plan de table",
    },
  },
  welcome: {
    title: "Bienvenue, {title}",
    description: "Votre site est prêt. Publiez-le et partagez vos liens.",
    unpublish: "Dépublier",
    publish: "Publier le site",
    unpublishedTitle: "Site dépublié",
    unpublishedDesc: "Votre site n'est plus accessible publiquement",
    publishedTitle: "Site publié !",
    publishedDesc: "Votre site est maintenant visible par tous",
    publishErrorTitle: "Publication impossible",
    publishErrorDesc: "Impossible de modifier le statut de publication. Veuillez réessayer.",
    status: "Statut",
    online: "En ligne",
    draft: "Brouillon",
    publiclyVisible: "Visible publiquement",
    previewOnly: "Preview uniquement",
    template: "Modèle",
    currentStyle: "Style actuel",
    plan: "Plan",
    activeBilling: "Facturation active",
    preview: "Prévisualisation",
    previewDesc: "Accessible même en brouillon.",
    openPreview: "Ouvrir la preview",
    publicSite: "Site public",
    publishToActivate: "Publiez pour l'activer",
    viewSite: "Voir le site",
    administration: "Administration",
    administrationDesc: "Accédez aux modules de gestion.",
    dashboard: "Tableau de bord",
    editInvitation: "Modifier l'invitation",
    templatesAndDesign: "Modèles et design",
  },
  designPage: {
    title: "Design du site",
    description: "Personnalisez l'apparence et le contenu de votre site.",
    back: "Retour",
    preview: "Aperçu",
    siteSettings: "Réglages du site",
    siteBlocks: "Blocs du site",
    siteBlocksDesc: "Ces sections correspondent directement à ce que vos invités voient sur le site.",
    siteLanguage: "Langue du site",
    siteLanguageDesc: "Choisissez la langue principale du site. Les textes par défaut, les libellés et les dates s'alignent automatiquement.",
    save: "Enregistrer",
    saving: "Enregistrement...",
    template: "Modèle",
    templateDesc: "Choisissez le style général de votre site.",
    chooseTemplate: "Choisir un modèle",
    applyTemplate: "Choisir ce modèle",
    applyingTemplate: "Changement en cours...",
    premiumSuffix: "Premium",
    logo: "Logo",
    logoDesc: "Ajoutez votre logo ou monogramme. Il apparaîtra en haut du site.",
    removeLogo: "Supprimer le logo",
    uploadLogo: "Importer un logo",
    logoPreview: "Aperçu du logo",
    logoFallback: "Texte affiché si aucun logo n'est importé",
    logoFallbackPlaceholder: "Ex : A & M",
    logoStyle: "Profil du logo texte",
    previewCard: "Aperçu",
    colors: "Couleurs et écriture",
    colorsDesc: "Choisissez les couleurs et le style d'écriture de votre site. Les changements s'affichent tout de suite.",
    colorPalette: "Palette de couleurs",
    primary: "Primaire",
    secondary: "Secondaire",
    fontFamily: "Style d'écriture",
    fontPreview: "Exemple de rendu pour votre site",
    buttonStyle: "Style des boutons",
    buttonShape: "Forme des boutons",
    photos: "Photos du site",
    homePhoto: "Photo d'accueil",
    couplePhoto: "Photo secondaire du couple",
    remove: "Supprimer",
    home: "Accueil",
    homeDesc: "La première impression de votre site : titre, photo, date du mariage et bouton d'action.",
    siteTitle: "Titre du site",
    titleLabel: "Titre",
    subtitle: "Sous-titre",
    heroButton: "Texte du bouton principal",
    dateCountdown: "Date et compte à rebours",
    displayedDateText: "Texte de date affiché",
    countdownDate: "Date du compte à rebours",
    countdownHint: "Référence utilisée par le compteur principal.",
    showSection: "Afficher la section",
    rsvpVisibility: "Affiche ou masque le bloc RSVP sur le site.",
    descriptionLabel: "Description",
    rsvpButton: "Bouton RSVP",
    gifts: "Cadeaux",
    giftsVisibility: "Affiche ou masque la section cadeaux sur le site.",
    introText: "Texte d'introduction",
    giftList: "Liste des cadeaux",
    giftsManagedElsewhere: "Les cadeaux eux-mêmes se gèrent dans la page « Cadeaux ».",
    openGiftsPage: "Ouvrir la page Cadeaux",
    story: "Histoire",
    storyVisibility: "Affiche ou masque la section histoire sur le site.",
    textLabel: "Texte",
    gallery: "Galerie photos",
    galleryVisibility: "Affiche ou masque la galerie photos sur le site.",
    galleryPhotos: "Photos de la galerie",
    galleryPhotosHint: "Ajoutez jusqu'à {count} photos pour cette section.",
    noGalleryPhotos: "Aucune photo ajoutée pour l'instant.",
    nearbyStay: "Hébergement à proximité",
    accommodationVisibility: "Affiche ou masque la section hébergement sur le site.",
    addressItem: "Adresse {index}",
    accommodationNamePlaceholder: "Nom du lieu ou de l'hôtel",
    fullAddressPlaceholder: "Adresse complète",
    bookingLinkPlaceholder: "Lien Google Maps ou réservation (optionnel)",
    addAddress: "Ajouter une adresse",
    locations: "Lieux & Accès",
    locationsVisibility: "Affiche ou masque la section des lieux sur le site.",
    locationItem: "Lieu {index}",
    locationTitlePlaceholder: "Titre du lieu",
    addressPlaceholder: "Adresse",
    descriptionPlaceholder: "Description",
    addLocation: "Ajouter un lieu",
    lodgingSuggestions: "Suggestions de logement",
    lodgingSuggestionsDesc: "Ajoutez ici les hôtels ou logements recommandés autour de chaque lieu.",
    addLocationFirst: "Ajoutez d'abord un lieu dans « Lieux & Accès » pour pouvoir proposer des hébergements.",
    addAccommodation: "+ Ajouter un hébergement",
    noAccommodationForLocation: "Aucun hébergement ajouté pour ce lieu.",
    locationAddressHint: "Ajoutez l'adresse du lieu pour mieux vous repérer.",
    hotelNamePlaceholder: "Nom de l'hôtel ou du logement",
    distancePlaceholder: "Adresse ou distance",
    reservationLinkPlaceholder: "Lien de réservation (optionnel)",
    schedule: "Programme",
    scheduleVisibility: "Affiche ou masque la section déroulé sur le site.",
    stepItem: "Étape {index}",
    timePlaceholder: "Horaire",
    addStep: "Ajouter une étape",
    newStep: "Nouvelle étape",
    fund: "Cagnotte",
    fundVisibility: "Affiche ou masque la section cagnotte sur le site.",
    contributionOptions: "Options de contribution",
    contributionOptionsDesc: "Gérez ici les moyens de participation affichés à vos invités sur la cagnotte.",
    invitationDressCode: "Dress code de l'invitation",
    invitationDressCodeDesc: "Ce bloc n'apparaît pas dans l'aperçu du site. Il s'affiche seulement sur l'invitation personnalisée de chaque invité.",
    invitationDressCodeVisibility: "Masquez complètement ce bloc si vous n'avez pas de consigne vestimentaire.",
    guestDressCode: "Texte affiché aux invités",
    guestDressCodePlaceholder: "Ex: Tenue de cocktail – Tons pastel appréciés",
    publicPreview: "Aperçu",
    publicPreviewTitle: "Preview public",
    tour: {
      editPanelTitle: "Panneau d'édition",
      editPanelDesc: "Modifiez ici les couleurs, polices, images et textes de votre site. Chaque section est modifiable.",
      livePreviewTitle: "Aperçu en direct",
      livePreviewDesc: "Cliquez ici pour voir votre site tel que vos invités le verront. Les changements sont visibles en temps réel.",
      publishTitle: "Publier vos changements",
      publishDesc: "Vos changements sont enregistrés directement dans cet espace.",
    },
  },
  helpCenter: {
    title: "Centre d'aide",
    searchPlaceholder: "Rechercher une question...",
    noResults: "Aucun résultat pour « {search} »",
    noResultsHint: "Essayez avec d'autres mots-clés",
    footer: "Besoin de plus d'aide ? Contactez-nous à",
    categories: {
      invitation: "Design",
      guests: "Invités",
      gifts: "Cadeaux",
      sharing: "Partage",
      subscription: "Abonnement",
      pages: "Pages",
    },
    items: [
      { category: "invitation", question: "Comment modifier les textes de mon site ?", answer: "Allez dans « Design ». Chaque bloc du site a ses propres champs. Modifiez les textes ou choisissez un style, puis vos changements sont enregistrés dans cet espace.", link: { label: "Ouvrir Design", href: "/design" } },
      { category: "invitation", question: "Comment changer les couleurs et le style d'écriture ?", answer: "Dans la page Design, ouvrez la section « Couleurs et écriture ». Vous pouvez choisir une palette, un style d'écriture et la forme des boutons.", link: { label: "Ouvrir Design", href: "/design" } },
      { category: "invitation", question: "Comment changer de modèle ?", answer: "Rendez-vous dans « Templates » pour voir les modèles disponibles. Vous pouvez aussi changer de modèle depuis la section « Modèle » dans Design.", link: { label: "Voir les modèles", href: "/templates" } },
      { category: "invitation", question: "Comment ajouter ou changer mon logo ?", answer: "Dans Design, ouvrez la section « Logo ». Importez un logo ou définissez un texte de remplacement, puis choisissez un style de logo texte si besoin.", link: { label: "Ouvrir Design", href: "/design" } },
      { category: "invitation", question: "Comment modifier le haut de la page ?", answer: "Dans Design, ouvrez la section « Haut de page ». Vous pouvez y choisir l'organisation du haut de page et l'espace avant le contenu principal.", link: { label: "Ouvrir Design", href: "/design" } },
      { category: "invitation", question: "Comment ajouter des lieux et des hébergements ?", answer: "Dans Design, ajoutez vos lieux dans « Lieux & Accès », puis vos adresses utiles dans « Hébergement à proximité ».", link: { label: "Ouvrir Design", href: "/design" } },
      { category: "guests", question: "Comment ajouter des invités ?", answer: "Allez dans « Invités », puis cliquez sur « Ajouter un invité ». Vous pouvez aussi exporter votre liste au format CSV.", link: { label: "Gérer les invités", href: "/guests" } },
      { category: "guests", question: "Comment suivre les RSVP ?", answer: "Les réponses RSVP apparaissent automatiquement dans la page Invités avec un statut. Utilisez les filtres pour les trier rapidement.", link: { label: "Voir les invités", href: "/guests" } },
      { category: "guests", question: "Comment envoyer les invitations ?", answer: "Chaque invité dispose d'un lien personnalisé. Depuis le tableau des invités, vous pouvez ouvrir l'invitation ou partager son lien.", link: { label: "Gérer les invités", href: "/guests" } },
      { category: "gifts", question: "Comment gérer la liste de cadeaux ?", answer: "Dans « Cadeaux », ajoutez des cadeaux avec nom, description et prix. Les invités peuvent ensuite les réserver depuis le site public.", link: { label: "Gérer les cadeaux", href: "/gifts" } },
      { category: "gifts", question: "Comment fonctionne la cagnotte ?", answer: "La cagnotte permet à vos invités de contribuer via les moyens configurés. Vous suivez ensuite les contributions depuis votre espace Daylora." },
      { category: "sharing", question: "Comment partager mon site ?", answer: "Votre site est accessible via un lien unique. Publiez-le quand vous êtes prêt, puis partagez ce lien à vos invités." },
      { category: "sharing", question: "Comment publier ou dépublier mon site ?", answer: "Rendez-vous dans « Paramètres » pour activer ou désactiver la publication du site.", link: { label: "Ouvrir les paramètres", href: "/settings" } },
      { category: "subscription", question: "Comment passer au plan Premium ?", answer: "Rendez-vous dans « Facturation » pour débloquer les templates Premium, plus d'invités, plus de cadeaux et davantage d'options.", link: { label: "Voir la facturation", href: "/billing" } },
      { category: "subscription", question: "Quelles sont les différences entre les plans ?", answer: "Le plan gratuit permet de démarrer rapidement. Premium débloque davantage de personnalisation, de contenus et de capacité.", link: { label: "Comparer les plans", href: "/billing" } },
      { category: "subscription", question: "Comment fonctionne le parrainage ?", answer: "Chaque utilisateur peut partager un code de parrainage donnant une réduction sur Premium.", link: { label: "Voir la facturation", href: "/billing" } },
      { category: "pages", question: "Comment ajouter des pages personnalisées ?", answer: "Depuis « Pages », créez des pages libres pour ajouter des informations pratiques, un dress code ou d'autres contenus.", link: { label: "Gérer les pages", href: "/pages" } },
      { category: "pages", question: "Comment configurer le menu de mon site ?", answer: "Dans « Site & Menus », choisissez les sections à afficher et organisez la navigation principale.", link: { label: "Configurer le site", href: "/site" } },
    ],
  },
} as const;
