export const NLS_EN = {
  siteLanguagePack: {
    language: "en" as const,
    locale: "en-US",
    stepLabels: ["Wedding", "Style", "Photos", "Gallery", "Preview", "Account"],
    menuLabels: {
      home: "Home",
      gifts: "Gifts",
      story: "Story",
      gallery: "Photos",
      accommodation: "Stay",
      location: "Venue",
      program: "Schedule",
    },
    texts: {
      heroSubtitle: "The Wedding of",
      heroCta: "Confirm your attendance",
      rsvpTitle: "CONFIRM YOUR ATTENDANCE",
      rsvpDescription: "We would be delighted to celebrate with you",
      rsvpButton: "I confirm my attendance",
      navRsvp: "RSVP",
      navCagnotte: "Fund",
      locationTitle: "VENUE & ACCESS",
      locationDescription: "Everything you need to join us easily",
      accommodationTitle: "PLACES TO STAY NEARBY",
      accommodationDescription: "Find a few recommended addresses to stay nearby.",
      programTitle: "SCHEDULE",
      programDescription: "A quick overview of our day",
      storyTitle: "OUR STORY",
      storyBody: "Their story began a few years ago, with a simple encounter that turned into a beautiful adventure. Today, they are getting ready to say “I do” surrounded by the people they love.",
      galleryTitle: "PHOTO GALLERY",
      galleryDescription: "A few moments captured before the big day.",
      giftsTitle: "GIFT LIST",
      giftsDescription: "A few ideas for those who would like to treat us.",
      cagnotteTitle: "WEDDING FUND",
      cagnotteDescription: "Your presence is the greatest gift. If you would like to contribute to our honeymoon or our new beginning, you can join our wedding fund.",
      cagnotteBackLabel: "Back",
      cagnotteSubmitLabel: "Contribute",
      invitationGreeting: "We are delighted to invite you",
      invitationPrelude: "to celebrate the union of",
      invitationMessage: "This day would not be the same without your presence by our side.",
      invitationSubmessage: "Come as you are, with a light heart and ready to celebrate.",
      invitationCagnotteTitle: "Wedding fund",
      invitationCagnotteDescription: "Your presence is the greatest gift. If you would still like to contribute, a wedding fund has been set up to help us build our future together.",
      invitationCagnotteButton: "Contribute",
      invitationFooterNote: "Please confirm your attendance before the indicated date. We cannot wait to celebrate with you.",
      footerTitle: "We can't wait to see you",
      footerSubtitle: "Thank you for being part of this adventure.",
      footerCopyright: "© 2026. All rights reserved.",
    },
    sections: {
      locationItems: [
        { title: "Civil ceremony", address: "Lille City Hall — 10 Rue Pierre Mauroy", description: "Please arrive around 2:30 PM to welcome guests." },
        { title: "Reception", address: "Château de la Verrière — Salle des Roses", description: "Cocktail and dinner starting at 6:00 PM." },
      ],
      programItems: [
        { time: "14:30", title: "Guest arrival", description: "Welcome, seating and family photos." },
        { time: "15:00", title: "Ceremony", description: "Vows, rings and the couple's exit." },
        { time: "18:30", title: "Cocktail & Dinner", description: "Drinks, dinner and celebration." },
      ],
    },
    invitation: {
      pageTitle: "Invitation",
      loading: "Loading...",
      notFoundTitle: "Invitation not found",
      notFoundDescription: "Please check the link or contact the couple.",
      people: "people",
      person: "person",
      table: "Table",
      invitationType: "Invitation type",
      checkInLink: "Check-in link",
    },
  },
  adminLayout: {
    brand: "Daylora Admin",
    back: "Back",
    design: "Design",
    languageLabel: "Language",
    languageFr: "FR",
    languageEn: "EN",
    editLive: "Edit live",
    viewSite: "View website",
    helpCenter: "Help center",
    weddingManagement: "Wedding management",
    logout: "Log out",
    logoutTitle: "Log out",
    pageLabels: {
      templates: "Templates",
      design: "Live editor",
      guests: "Guests",
      guestExperience: "Guest experience",
      billing: "Billing",
      gifts: "Gifts",
      site: "Site & Navigation",
      checkInOps: "Event day check-in",
      home: "Home",
      fallback: "Daylora workspace",
    },
    nav: {
      home: "Home",
      dashboard: "Dashboard",
      design: "Design",
      guests: "Guests",
      guestExperience: "Guest experience",
      checkInOps: "Event day check-in",
      templates: "Templates",
      site: "Site & Navigation",
      gifts: "Gifts",
      emails: "Emails",
      billing: "Billing",
      feedback: "Feedback",
      settings: "Settings",
    },
  },
  dashboard: {
    welcomeSuffix: "your story begins here.",
    welcomeSubtitle: "Welcome to the creation of your unforgettable day",
    congratulationsSuffix: "your beautiful story continues.",
    weddingHappened: "Your wedding has happened — enjoy every memory.",
    countdownLabel: "Days to go",
    countdownDay: "day",
    countdownDays: "days",
    nextStepLabel: "Next step",
    steps: {
      chooseDesign: "Choose a design",
      chooseDesignDesc: "Select a template to bring your website to life.",
      completeInfo: "Complete your details",
      completeInfoDesc: "Add your wedding date and key details.",
      addGuests: "Add your guests",
      addGuestsDesc: "Start building your guest list.",
      publish: "Publish your website",
      publishDesc: "Your site is ready — share it with your loved ones.",
    },
    linkCopied: "Link copied",
    fullMode: "Full mode",
    simplify: "Simplify",
    kpis: {
      guests: "Guests",
      guestsHint: "RSVPs received",
      confirmed: "Confirmed",
      confirmedHint: "Attending",
      pending: "Pending",
      pendingHint: "To follow up",
      declined: "Declined",
      declinedHint: "Unavailable",
    },
    tour: {
      welcomeTitle: "Welcome to Daylora!",
      welcomeDesc: "Here you will find a personalized message and the link to your wedding website.",
      statsTitle: "Your stats",
      statsDesc: "Track guests, confirmations and declines at a glance.",
      progressTitle: "Your progress",
      progressDesc: "This checklist guides you step by step so your site is ready to share.",
    },
  },
  checklist: {
    title: "Your progress",
    completedSteps: "{done} of {total} steps completed",
    cta: "Do it",
    steps: {
      template: {
        label: "Choose a design",
        description: "Select the perfect template for your wedding",
      },
      info: {
        label: "Key details",
        description: "Date, venue and your story",
      },
      guests: {
        label: "Add guests",
        description: "Import or add your guest list",
      },
      features: {
        label: "Enable modules",
        description: "Fund, gift list, guest book",
      },
      publish: {
        label: "Publish the website",
        description: "Make your website visible to your guests",
      },
    },
  },
  widgets: {
    availability: {
      present: "Attending",
      absent: "Declined",
      pending: "Pending",
    },
    partySize: {
      solo: "Solo (1)",
      couple: "Couple (2)",
    },
    tablePlan: {
      assigned: "Assigned",
      unassigned: "Unassigned",
    },
    cards: {
      totalGuests: "Total guests",
      totalGuestsDesc: "{count} responses",
      declined: "Declined",
      declinedDesc: "Unavailable guests",
      confirmed: "Confirmed",
      confirmedDesc: "{count} total people",
      siteDesign: "Website & design",
      siteDesignValue: "Customize",
      siteDesignDesc: "Edit your website",
      clickToFilter: "(click to filter)",
    },
    charts: {
      availability: "Availability split",
      groupSize: "Group sizes",
      tablePlan: "Table plan",
    },
  },
  welcome: {
    title: "Welcome, {title}",
    description: "Your website is ready. Publish it and share your links.",
    unpublish: "Unpublish",
    publish: "Publish website",
    unpublishedTitle: "Website unpublished",
    unpublishedDesc: "Your website is no longer publicly accessible",
    publishedTitle: "Website published!",
    publishedDesc: "Your website is now visible to everyone",
    publishErrorTitle: "Could not publish",
    publishErrorDesc: "We could not change the publication status. Please try again.",
    status: "Status",
    online: "Online",
    draft: "Draft",
    publiclyVisible: "Publicly visible",
    previewOnly: "Preview only",
    template: "Style",
    currentStyle: "Current style",
    plan: "Plan",
    activeBilling: "Active billing",
    preview: "Preview",
    previewDesc: "Available even in draft mode.",
    openPreview: "Open preview",
    publicSite: "Public website",
    publishToActivate: "Publish to activate it",
    viewSite: "View website",
    administration: "Administration",
    administrationDesc: "Access your management modules.",
    dashboard: "Dashboard",
    editInvitation: "Edit website",
    templatesAndDesign: "Styles and design",
  },
  designPage: {
    title: "Website design",
    description: "Customize the look and content of your website.",
    back: "Back",
    preview: "Preview",
    siteSettings: "Website settings",
    siteBlocks: "Website sections",
    siteBlocksDesc: "These sections directly match what your guests see on the website.",
    siteLanguage: "Website language",
    siteLanguageDesc: "Choose the main language of the website. Default texts, labels and dates update automatically.",
    save: "Save",
    saving: "Saving...",
    template: "Style",
    templateDesc: "Choose the overall style of your website.",
    chooseTemplate: "Choose a style",
    applyTemplate: "Choose this style",
    applyingTemplate: "Updating...",
    premiumSuffix: "Premium",
    logo: "Logo",
    logoDesc: "Add your logo or monogram. It will appear at the top of the website.",
    removeLogo: "Remove logo",
    uploadLogo: "Upload a logo",
    logoPreview: "Logo preview",
    logoFallback: "Text shown when no logo is uploaded",
    logoFallbackPlaceholder: "Example: A & M",
    logoStyle: "Text logo style",
    previewCard: "Preview",
    colors: "Colors and text style",
    colorsDesc: "Choose the colors and text style of your website. Changes appear right away.",
    colorPalette: "Color palette",
    primary: "Primary",
    secondary: "Secondary",
    fontFamily: "Text style",
    fontPreview: "Website preview example",
    buttonStyle: "Button style",
    buttonShape: "Button shape",
    photos: "Website photos",
    homePhoto: "Cover photo",
    couplePhoto: "Secondary couple photo",
    remove: "Remove",
    home: "Home",
    homeDesc: "The first impression of your website: title, photo, date and main button.",
    siteTitle: "Website title",
    titleLabel: "Title",
    subtitle: "Subtitle",
    heroButton: "Main button text",
    dateCountdown: "Date & countdown",
    displayedDateText: "Displayed date text",
    countdownDate: "Countdown date",
    countdownHint: "Reference used by the main countdown.",
    showSection: "Show section",
    rsvpVisibility: "Show or hide the RSVP block on the website.",
    descriptionLabel: "Description",
    rsvpButton: "RSVP button",
    gifts: "Gifts",
    giftsVisibility: "Show or hide the gifts section on the website.",
    introText: "Intro text",
    giftList: "Gift list",
    giftsManagedElsewhere: "The gifts themselves are managed in the “Gifts” page.",
    openGiftsPage: "Open Gifts page",
    story: "Story",
    storyVisibility: "Show or hide the story section on the website.",
    textLabel: "Text",
    gallery: "Photo gallery",
    galleryVisibility: "Show or hide the photo gallery on the website.",
    galleryPhotos: "Gallery photos",
    galleryPhotosHint: "Add up to {count} photos for this section.",
    noGalleryPhotos: "No photo added yet.",
    nearbyStay: "Places to stay nearby",
    accommodationVisibility: "Show or hide the accommodation section on the website.",
    addressItem: "Address {index}",
    accommodationNamePlaceholder: "Venue or hotel name",
    fullAddressPlaceholder: "Full address",
    bookingLinkPlaceholder: "Google Maps or booking link (optional)",
    addAddress: "Add an address",
    locations: "Venue & access",
    locationsVisibility: "Show or hide the venue section on the website.",
    locationItem: "Venue {index}",
    locationTitlePlaceholder: "Venue title",
    addressPlaceholder: "Address",
    descriptionPlaceholder: "Description",
    addLocation: "Add a venue",
    lodgingSuggestions: "Stay suggestions",
    lodgingSuggestionsDesc: "Add recommended hotels or stays around each venue here.",
    addLocationFirst: "First add a venue in “Venue & access” before suggesting accommodation.",
    addAccommodation: "+ Add accommodation",
    noAccommodationForLocation: "No accommodation added for this venue.",
    locationAddressHint: "Add the venue address to make it easier to identify.",
    hotelNamePlaceholder: "Hotel or stay name",
    distancePlaceholder: "Address or distance",
    reservationLinkPlaceholder: "Booking link (optional)",
    schedule: "Schedule",
    scheduleVisibility: "Show or hide the schedule section on the website.",
    stepItem: "Step {index}",
    timePlaceholder: "Time",
    addStep: "Add a step",
    newStep: "New step",
    fund: "Fund",
    fundVisibility: "Show or hide the fund section on the website.",
    contributionOptions: "Contribution options",
    contributionOptionsDesc: "Manage the participation methods shown to your guests on the fund page.",
    invitationDressCode: "Invitation dress code",
    invitationDressCodeDesc: "This block does not appear in the website preview. It only appears on each guest's personalized invitation.",
    invitationDressCodeVisibility: "Hide this block entirely if you do not have a dress code.",
    guestDressCode: "Text shown to guests",
    guestDressCodePlaceholder: "Example: Cocktail attire – pastel tones appreciated",
    publicPreview: "Preview",
    publicPreviewTitle: "Public preview",
    tour: {
      editPanelTitle: "Editing panel",
      editPanelDesc: "Edit your website colors, fonts, images and texts here. Each section can be customized.",
      livePreviewTitle: "Live preview",
      livePreviewDesc: "Click here to see your website exactly as your guests will see it. Changes are visible in real time.",
      publishTitle: "Publish your changes",
      publishDesc: "Your changes are saved directly from this editing space.",
    },
  },
  helpCenter: {
    title: "Help center",
    searchPlaceholder: "Search a question...",
    noResults: "No results for “{search}”",
    noResultsHint: "Try a different keyword",
    footer: "Need more help? Contact us at",
    categories: {
      invitation: "Design",
      guests: "Guests",
      gifts: "Gifts",
      sharing: "Sharing",
      subscription: "Subscription",
      pages: "Pages",
    },
    items: [
      { category: "invitation", question: "How do I edit the texts on my website?", answer: "Go to “Design”. Each block of the website has its own fields. Edit the texts or choose a style, and your changes are saved from this editing space.", link: { label: "Open Design", href: "/design" } },
      { category: "invitation", question: "How do I change colors and text style?", answer: "In Design, open “Colors and text style”. You can choose a palette, a text style and the button shape.", link: { label: "Open Design", href: "/design" } },
      { category: "invitation", question: "How do I change style?", answer: "Go to “Templates” to view the available styles. You can also change the style from the “Style” section in Design.", link: { label: "View styles", href: "/templates" } },
      { category: "invitation", question: "How do I add or change my logo?", answer: "In Design, open the “Logo” section. Upload an image logo or define fallback text, then choose a text logo style if needed.", link: { label: "Open Design", href: "/design" } },
      { category: "invitation", question: "How do I change the top of the page?", answer: "In Design, open “Top of the page”. You can choose the layout of the top area and the space before the main content.", link: { label: "Open Design", href: "/design" } },
      { category: "invitation", question: "How do I add venues and nearby stays?", answer: "In Design, add your venues in “Venue & Access”, then add useful addresses in “Places to stay nearby”.", link: { label: "Open Design", href: "/design" } },
      { category: "guests", question: "How do I add guests?", answer: "Go to “Guests”, then click “Add guest”. You can also export your guest list as CSV.", link: { label: "Manage guests", href: "/guests" } },
      { category: "guests", question: "How do I track RSVPs?", answer: "RSVP replies automatically appear in the Guests page with a status. Use filters to sort them quickly.", link: { label: "View guests", href: "/guests" } },
      { category: "guests", question: "How do I send invitations?", answer: "Each guest has a personalized invitation link. From the guest list, you can open the invitation or share the link.", link: { label: "Manage guests", href: "/guests" } },
      { category: "gifts", question: "How do I manage the gift list?", answer: "In “Gifts”, add gifts with a name, description and price. Guests can then reserve them from the public site.", link: { label: "Manage gifts", href: "/gifts" } },
      { category: "gifts", question: "How does the fund work?", answer: "The fund lets guests contribute using the configured payment methods. You can then track contributions from your Daylora space." },
      { category: "sharing", question: "How do I share my website?", answer: "Your site is available through a unique link. Publish it when ready, then share that link with your guests." },
      { category: "sharing", question: "How do I publish or unpublish my website?", answer: "Go to “Settings” to enable or disable website publication.", link: { label: "Open settings", href: "/settings" } },
      { category: "subscription", question: "How do I upgrade to Premium?", answer: "Go to “Billing” to unlock Premium templates, more guests, more gifts and additional options.", link: { label: "Open billing", href: "/billing" } },
      { category: "subscription", question: "What are the differences between plans?", answer: "The free plan lets you get started quickly. Premium unlocks more customization, more content and more capacity.", link: { label: "Compare plans", href: "/billing" } },
      { category: "subscription", question: "How does referral work?", answer: "Each user can share a referral code that gives a discount on Premium.", link: { label: "Open billing", href: "/billing" } },
      { category: "pages", question: "How do I add custom pages?", answer: "From “Pages”, create free pages to add practical information, a dress code or any extra content.", link: { label: "Manage pages", href: "/pages" } },
      { category: "pages", question: "How do I configure the website menu?", answer: "In “Site & Menus”, choose which sections to display and organize the main navigation.", link: { label: "Configure site", href: "/site" } },
    ],
  },
} as const;
